pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '/var/jenkins_home/maven/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Test state'
                //sh '/var/jenkins_home/maven/bin/mvn test'
            }
            //post {
            //    always {
            //        junit 'target/surefire-reports/*.xml'
            //    }
            //}
        }
        stage('Deliver') {
            steps {
                echo 'Deliver state'
                //sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
